version: '3.1'

volumes:
  mysql_data:
  mongo_data:

services:

  mysql:
    image: mysql
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'

  eureka-server:
    image: eureka-server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  clientes:
    image: cliente-service
    build: ./clientes
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongo:27017/clientes
    depends_on:
      - mongo
      - eureka-server

  libros:
    image: libro-service
    build: ./libros
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/libros?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql

  prestamos:
    image: prestamo-service
    build: ./prestamos
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/prestamos?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql

  gateway:
    image: gateway-service
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - libros
      - clientes
      - prestamos