version: '3.1'

volumes:
  mysql_data:
  mongo_data:
  keycloak_data_1:

services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command:
      - start-dev
    volumes:
      - keycloak_data_1:/opt/keycloak/data/
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  mysql:
    image: mysql
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'

  eureka-server:
    image: eureka-server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  clientes:
    image: cliente-service
    build: ./clientes
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.data.mongodb.uri=mongodb://mongo:27017/clientes
    depends_on:
      - mongo
      - eureka-server

  libros:
    image: libro-service
    build: ./libros
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/libros?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql

  prestamos:
    image: prestamo-service
    build: ./prestamos
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/prestamos?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql

  gateway:
    image: gateway-service
    build: ./gateway
    ports:
      - "8080:8082"
    environment:
      - server.port=8082
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/tutorial-api
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/tutorial-api/protocol/openid-connect/certs

    depends_on:
      - eureka-server
      - libros
      - clientes
      - prestamos
      - keycloak

